# Generated by Django 6.1.2 on 2026-10-07 14:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_plataforma', models.DecimalField(decimal_places=2, default=Decimal('17.00'), help_text='Percentual cobrado em cima do preço de cada ingresso. Ex.: 17.00', max_digits=5, verbose_name='Taxa da plataforma (%)')),
                ('aliquota_imposto', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Imposto do Ingressou, calculado SOMENTE sobre a taxa da plataforma. Ajuste com seu contador.', max_digits=5, verbose_name='Alíquota de imposto sobre a taxa (%)')),
                ('taxa_mp_pix', models.DecimalField(decimal_places=2, default=Decimal('0.99'), max_digits=5, verbose_name='Taxa Mercado Pago — Pix (%)')),
                ('taxa_mp_cartao', models.DecimalField(decimal_places=2, default=Decimal('4.99'), max_digits=5, verbose_name='Taxa Mercado Pago — Cartão (%)')),
                ('minutos_expiracao_pedido', models.PositiveIntegerField(default=30, verbose_name='Minutos para expirar pedido pendente')),
            ],
            options={
                'verbose_name': 'Configuração da plataforma',
                'verbose_name_plural': 'Configuração da plataforma',
            },
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produtor',
                'verbose_name_plural': 'Produtores',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField(verbose_name='Data e hora de início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de término')),
                ('local', models.CharField(max_length=300)),
                ('cidade', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('publicado', models.BooleanField(default=False, help_text='Só eventos publicados aparecem na loja.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.produtor')),
            ],
            options={
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço que o PRODUTOR recebe exatamente. A taxa da plataforma é somada no checkout.', max_digits=10)),
                ('quantidade_total', models.PositiveIntegerField()),
                ('quantidade_vendida', models.PositiveIntegerField(default=0)),
                ('max_por_pedido', models.PositiveIntegerField(default=10, verbose_name='Máximo por pedido')),
                ('ativo', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_ingresso', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Tipo de ingresso',
                'verbose_name_plural': 'Tipos de ingresso',
            },
        ),
    ]
