# Generated by Django 6.1.2 on 2026-10-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('show', 'Show'), ('festa', 'Festa'), ('teatro', 'Teatro'), ('esporte', 'Esporte'), ('curso', 'Curso/Workshop'), ('outros', 'Outros')], default='show', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Evento em destaque na home'),
        ),
    ]
