# Generated by Django 6.1.2 on 2026-10-07 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_categoria_evento_destaque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produtor',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Conta CNPJ do produtor no site — dá acesso à área do produtor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('show', 'Shows'), ('festa', 'Festas'), ('teatro', 'Teatros e Espetáculos'), ('esporte', 'Esportes'), ('standup', 'Stand Up Comedy'), ('congresso', 'Congressos e Palestras'), ('passeio', 'Passeios e Tours'), ('infantil', 'Infantil'), ('curso', 'Cursos e Workshops'), ('gastronomia', 'Gastronomia'), ('religiao', 'Religião e Espiritualidade'), ('festival', 'Festivais'), ('online', 'Eventos Online'), ('outros', 'Outros')], default='show', max_length=20),
        ),
    ]
