# Generated by Django 6.1.2 on 2026-10-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_produtor_usuario_alter_evento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, help_text='Banner MAIOR — aparece no carrossel da página inicial (ex.: 1600x820). Se vazio, usa o banner menor.', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Banner MENOR — aparece nos cards de eventos (proporção 16:9, ex.: 800x450).', null=True, upload_to='eventos/'),
        ),
    ]
