# Generated by Django 6.1.2 on 2026-10-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_banner_alter_evento_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimentoEvento',
            fields=[
            ],
            options={
                'verbose_name': 'Requerimento de evento',
                'verbose_name_plural': '📥 Requerimentos de eventos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eventos.evento',),
        ),
    ]
