# Generated by Django 6.1.2 on 2026-10-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_requerimentoevento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoingresso',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Tipo de ingresso', 'verbose_name_plural': 'Tipos de ingresso'},
        ),
        migrations.AddField(
            model_name='tipoingresso',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='0 = sempre à venda. 1, 2, 3... = abre quando o lote anterior esgotar.', verbose_name='Ordem do lote'),
        ),
    ]
