# Generated by Django 6.1.2 on 2026-10-08 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_tipoingresso_options_tipoingresso_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, help_text='Ex.: PIX enviado, comprovante nº, acordo especial', max_length=200)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repasse_controle', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Repasse ao produtor',
                'verbose_name_plural': 'Repasses aos produtores',
            },
        ),
    ]
