# Generated by Django 6.1.2 on 2026-10-09 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_repasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('free', 'Gratuita — cadastro direto'), ('paga', 'Paga — checkout Mercado Pago')], default='free', max_length=5)),
                ('preco', models.DecimalField(decimal_places=2, default=0, help_text='Só para lista PAGA: valor que o PRODUTOR recebe. A taxa da plataforma é somada no checkout.', max_digits=10)),
                ('quantidade_limite', models.PositiveIntegerField(verbose_name='Quantidade de vagas da lista')),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_vip', to='eventos.evento')),
                ('tipo_ingresso', models.OneToOneField(blank=True, help_text='Tipo de ingresso oculto que guarda o estoque da lista.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista_vip_origem', to='eventos.tipoingresso')),
            ],
            options={
                'verbose_name': 'Lista VIP',
                'verbose_name_plural': 'Listas VIP',
            },
        ),
    ]
