# Generated by Django 6.1.2 on 2026-10-07 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Cópia do preço no momento da compra (preços mudam, o histórico não).', max_digits=10)),
                ('tipo_ingresso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.tipoingresso')),
            ],
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qrcode', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='pedidos.itempedido')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('comprador_nome', models.CharField(max_length=200)),
                ('comprador_email', models.EmailField(max_length=254)),
                ('comprador_cpf', models.CharField(max_length=14)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=10)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('', 'Não definido'), ('pix', 'Pix'), ('cartao', 'Cartão de crédito')], default='', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Valor dos ingressos — repassado EXATO ao produtor.', max_digits=10)),
                ('taxa_plataforma', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total pago pelo comprador (subtotal + taxa).', max_digits=10)),
                ('custo_gateway', models.DecimalField(decimal_places=2, default=0, help_text='Taxa do Mercado Pago, calculada quando o pagamento é confirmado.', max_digits=10)),
                ('imposto', models.DecimalField(decimal_places=2, default=0, help_text='Imposto do Ingressou sobre a taxa da plataforma.', max_digits=10)),
                ('mp_payment_id', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='eventos.evento')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido'),
        ),
    ]
