# Generated by Django 6.1.2 on 2026-10-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprador_whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('', 'Não definido'), ('pix', 'Pix'), ('cartao', 'Cartão de crédito'), ('gratuito', 'Gratuito (lista VIP)')], default='', max_length=10),
        ),
    ]
