# Generated by Django 6.1.2 on 2026-10-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('comprador', 'Comprador (CPF) — compra ingressos'), ('produtor', 'Produtor (CNPJ) — cria eventos'), ('recepcao', 'Recepção — valida ingressos na entrada do evento')], max_length=10),
        ),
    ]
