# Generated by Django 6.1.2 on 2026-10-09 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_criar_admin_inicial'),
        ('eventos', '0007_repasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='eventos_liberados',
            field=models.ManyToManyField(blank=True, related_name='contas_portaria', to='eventos.evento', verbose_name='Eventos que pode bipar'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='produtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_portaria', to='eventos.produtor', verbose_name='Produtor dono (recepção)'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='documento',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
    ]
